hate = [
    'american front',
    'american nazi party',
    'aryan nation',
    'gas the kikes',
    'gas the kikes race war now',
    'kike',
    'kkk',
    'nazi',
    'nigger',
    'stormfront',
    'two seedline',
    'wetback',
    'holohoax',
    'holocaust denial',
    '14 words',
    'alt-lite',
    'alt-right',
    'american renaissance',
    'american vanguard',
    'blood and soil',
    'color of crime',
    'council of conservative citizens',
    'cultural marxism',
    'daily shoah',
    'daily stormer',
    'diversity is a code word for anti-white',
    'dual seedline',
    'ethnic cleansing',
    'ethnostate',
    'globalist jews',
    'great replacement',
    'hammerskin',
    'heil hitler',
    'identitarianism',
    'identity evropa',
    "it's okay to be white",
    'jewish question',
    'league of the south',
    'national socialism',
    'open borders for israel',
    'proud boys',
    'race realism',
    'race war',
    'racial holy war',
    'right wing death squads',
    'sieg heil',
    'southern nationalist',
    'swastika',
    'traditionalist worker party',
    'vdare',
    'war on whites',
    'we wuz kangz',
    'white civil rights',
    'white ethnostate',
    'white genocide',
    'white lives matter',
    'white nationalism',
    'white nationalist',
    'white pill',
    'white power',
    'white pride',
    'white pride worldwide',
    'white separatism',
    'white sharia',
    'you will not replace us',
    'zionist occupation government',
    'neo-confederate',
    'ethnonationalism',
    'ecofascism',
    'unite the right',
    'red ice tv',
    'black sun',
    'sonnenrad',
    'neo-nazi',
    '2083: a european declaration of independence',
    'radical islamic terror',
    'send them back',
    'civilization jihad',
    'american identity movement',
    'goy',
    'boogaloo',
    'dindu',
    'race and iq',
    'shitskins',
    'amerimutt',
    'lgbtp'
]

social_justice = [
    'black muslim',
    'anti-fascist',
    'reparations',
    'sex work',
    'sex ed',
    'sexual liberation',
    'colonialism',
    'repeal the ban',
    'no muslim ban ever',
    'i stand with ilhan',
    'stand with ilhan',
    'muslim solidarity',
    'american muslim',
    'muslim american',
    'abolish ice',
    'abolish the police',
    'no new jails',
    'defund the police',
    'black lives matter',
    'black trans lives matter',
    'black power',
    'black panthers',
    'racial justice',
    'racial injustice',
    'black liberation',
    'black is beautiful',
    'say her name',
    'black girls matter',
    'black in tech',
    'i stand with kaepernick',
    'oscars so white',
    'tell black stories',
    'believe black women',
    'no justice no peace',
    "i can't breathe",
    'say their names',
    'end police brutality',
    'no tech for ice',
    'movement for black lives',
    'hijab fashion',
    'muslim fashion',
    'muslim parenting',
    'antifascist',
    'black dissent',
    'patriarchy',
    'white supremacy',
    'lgbtq+',
    'bipoc',
    'qpoc',
    'queer',
    'digital justice',
    'anti-black',
    'antiracism',
    'electoral justice',
    'black excellence',
    'black august',
    'white fragility',
    'wypipo',
    'black identity extremists',
    'civil rights',
    'black hair',
    'for the culture'    
]

policies = [
    'miracle cancer treatment',
    'ecstasy',
    'sex',
    'sexual gratification',
    'make firearm',
    'recruit terrorists',
    'sexual fluids',
    'erotic massage services',
    "covid-19 doesn't exist",
    'eating disorders',
    'beheading',
    'extremism',
    'praise terrorists',
    'terrorist acts',
    'sexually unwanted acts',
    'chewing tobacco',
    'beastiality',
    'sex toys',
    'sexually explict content',
    'ethnic cleansing',
    'rifles',
    'make ammunition',
    'domestic violence',
    'pedophilia',
    'covid-19 guaranteed vaccine',
    'covid-19 from 5g',
    'cannibus coffee shops',
    'firearm scopes',
    'covid-19 asian food',
    'covid-19 vaccine kills people',
    'child abuse',
    'sex services',
    'self-harm',
    'minors vaping',
    'firearms',
    'vape pens',
    'get rich fast',
    'mephedrone',
    'incorrect election date',
    'voter supression',
    'automatic gun conversion kits',
    'suicide',
    'gun-grips',
    'forging official documents',
    'buy alcohol',
    'sexual acts',
    'terrorist recruitment',
    'buy organs',
    "covid-19 people don't die",
    'firearm silencer',
    'online gambling',
    'kidnapping',
    'heroin',
    'aids denial',
    'nude photo leaks',
    'making hard drugs',
    'make high capacity ammunition',
    'sexual fetishes',
    'handguns',
    'rape',
    'terrorist hostages',
    'child marriage',
    'mass shootings',
    'homemade silencer',
    'sex industry',
    'nipples',
    'police brutality',
    'upskirt',
    'firearm',
    'cannibalism',
    'cocaine',
    'bombings',
    'crime scene photos',
    'escort services',
    'sexual abuse',
    'disparaging',
    'e-cigarettes',
    'sexual device',
    'marijuana',
    'bullfighting swords in bull',
    'execution videos',
    'fetish content',
    'shootings',
    'steroids',
    'terrorist ideology',
    'coronavirus',
    'voter eligability',
    'incest',
    'rolling papers',
    'human torture',
    'covid-19 ritual',
    'covid-19 home remedy',
    'pornography',
    'vaping',
    'vapes',
    'dramatized rape scenes',
    'violent criminal organizations',
    'bongs',
    'miracle mineral solution',
    'generate fake credit card numbers',
    'voyeurism',
    'alcohol',
    'buy weed',
    'hunt with bombing',
    'covid',
    'racial discrimination',
    'genitalia',
    'abortion',
    'explosive vest',
    'swatting',
    'dog fighting',
    '3d print guns',
    'bump stocks',
    'animal mating',
    'bomb making',
    'ammunition clips',
    'miracle treatment',
    'prostitution',
    'covid-19',
    'video game terrorist mod',
    'harassment',
    'text your vote',
    'ammunition',
    'black salve',
    'covid-19 prayer',
    'intercourse',
    'masturbation',
    'robbery',
    'selling firearms',
    'cigarettes',
    'pipe bomb',
    "you'll make $50,000 tomorrow with this plan!",
    'anti-vaccination',
    'nudity',
    'package bombs',
    'molotov cocktail',
    'dogfighting',
    'firearm stocks',
    'fuck',
    'conterfeit passports',
    'cockfighting',
    'cigars',
    'buy drugs on the dark web',
    'sexual harassment',
    'online pharmacy no prescription',
    'terrorism',
    'crystal meth',
    'threads with firearms',
    'terrorist attack',
    'minors drinking alcohol',
]


noise = [
    'ttszozjqoits',
    'uomqddjzspns',
    'slmazdhuwcvd',
    'rkckgiahhgfa',
    'zszivsroacgs',
    'yqtdeovhxtgk',
    'dwdzqexksqlf',
    'cjqgkhdwykms',
    'hayaxuhefdgw',
    'ruuxxcgmdjpb',
    'hsqbhzvxegfw',
    'cihnmvqsyupl',
    'hnayxmumegoh',
    'ohssyskmiywy',
    'fjoooioxbudn',
    'aqrsmgtcrrsf',
    'wqjehgsaykxg',
    'miibtgsofrtv',
    'ffpqvoiocpnf',
    'iqpljloqyifq',
]

adhoc = [
    'white christian',
    "black christian",
    "christian parenting",
    "jewish parenting",
    "buddhist parenting",
    "buddhist fashion",
    "christian solidarity",
    "jewish solidarity",
    "buddhist",
    "buddhism",
    "scientology",
    "all lives matter",
    "blue lives matter",
    "Jewish Fashion",
    "Christian fashion",
    "sharia",
    "sexual education",
    "hiking gear reviews",
    "black nationalist",
    "black nationalism",
    "white nationalists",
    "niggers",
    "nazis",
    "kikes",
    "terrorists attack",
    "terrorists recruitment",
    "terrorists",
    "terrorism attack",
    "recruit terrorist",
    "praise terrorism",
    "praise terrorist",
    "terrorism acts",
    "terrorists acts",
    "terrorists hostage",
    "voter fraud",
    "stop the steal",
    "stolen election",
    "american muslims",
    "black muslims",
    "wetbacks",
    "neo-nazis",
    "neo-confederates",
    "neonazi",
    "neo nazi",
    "nazism",
    "nazi germany",
    "ww2 nazis",
    "nazi propoganda",
    "nazi scientist",
    "nazi extermination camps",
    "white pills",
    "christian american",
    "black chrsitian",
    "jewish american",
    "black jew",
    "black buddhist",
    "buddhist american",
    "rohingya genocide",
    "uyghur genocide",
    "yazidi genocide",
    "anti-vax",
    "anti-vaxx",
    'sex positive',
    "climate change",
    "climate denial",
    "blm",
    "homosexual",
    "sexuality"
]

social_justice = list(set([t.lower().strip() for t in social_justice]))
hate = list(set([t.lower().strip() for t in hate]))
policies = list(set([t.lower().strip() for t in policies]))

category2terms = {
    'social_justice' : social_justice,
    'hate' : hate,
    'policy' : policies,
    'noise' : noise,
    'adhoc' : adhoc,
}